stages:
  lint:
    enabled: false
  
  package: 
    enabled: true
    helmDir: deploy

  publish:
    enabled: true
    buildDir: build_images
  
  version:
    versionUpdates:
      - type: yaml
        file: deploy/values.yaml
        path: image.tag
      - type: yaml
        file: deploy/Chart.yaml
        path: version
      - type: yaml
        file: deploy/Chart.yaml
        path: appVersion
  
  deploy:
    enabled: false
    name: oddsbender-web-ui
    kubernetesConfig:
      name: oddsbender-cluster
      region: us-east-1
      credentialsId: jenkins-aws

environments:
  dev:
    stages:
      deploy:
        namespace: dev-oddsbender
        configFiles:
          - conf-deploy/common.values.yaml
          - conf-deploy/development.values.yaml
  prod:
    stages:
      deploy:
        namespace: prod-oddsbender
        configFiles:
          - conf-deploy/common.values.yaml
          - conf-deploy/production.values.yaml
