apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-ui.fullname" . }}
  labels:
    {{- include "web-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: https
  selector:
    {{- include "web-ui.selectorLabels" . | nindent 4 }}
