image:
  repository: 157485876214.dkr.ecr.us-east-2.amazonaws.com/web-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

basicAuth:
  authString: user:$apr1$BuKn3DhM$nGKMk0hwQOObznaIef0FJ0

command: 
  - '"/bin/bash", "-c"'
args:
  - exec nginx -g 'daemon off;'

nodeSelector:
  role: system
