image:
  repository: 157485876214.dkr.ecr.us-east-2.amazonaws.com/web-ui
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

basicAuth:
  authString: user:$apr1$av9fesol$zxfoN9w1IJg5NBULPWnVz/

command: 
  - '"/bin/bash", "-c"'
args:
  - exec nginx -g 'daemon off;'

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
  hosts:
    - host: oddsbender.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - oddsbender.com
      secretName: oddsbender-tls
  defaultBackend: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  role: system
