ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
  hosts:
    - host: dev.oddsbender.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - dev.oddsbender.com
      secretName: oddsbender-tls
  defaultBackend: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
