ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required
  hosts:
    - host: oddsbender.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - oddsbender.com
      secretName: oddsbender-tls
  defaultBackend: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

app:
  table_data_url: 'wss://user:BenderInternational@backend.oddsbender.com/ws/table_data'
  opportunity_url: 'wss://user:BenderInternational@backend.oddsbender.com/ws/opportunity_feed'